Repository Team-Shaka/Tree-House-iOS, pull requests merged in 2024-07, with the labels that each got.

#73 [Feat] #72 - CreateTreehouse 뷰 작업
  Treehouse/Treehouse.xcodeproj/project.pbxproj
  Treehouse/Treehouse/Global/Extension/String+.swift
  Treehouse/Treehouse/Global/Literals/StringLiterals.swift
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/CreateTreehouse/Contents.json
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/CreateTreehouse/img_createtreehouse.imageset/Contents.json
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/CreateTreehouse/img_createtreehouse.imageset/img_createtreehouse.png
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/CreateTreehouse/img_createtreehouse.imageset/img_createtreehouse@2x.png
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/CreateTreehouse/img_createtreehouse.imageset/img_createtreehouse@3x.png
  Treehouse/Treehouse/Presentation/CreateTreehouse/CreateTreehouseScene/Views/CreateTreeHallNameView.swift
  Treehouse/Treehouse/Presentation/CreateTreehouse/CreateTreehouseScene/Views/CreateTreehouseNameView.swift
  Treehouse/Treehouse/Presentation/CreateTreehouse/CreateTreehouseScene/Views/PreviewCreatedTreehouseView.swift
  Treehouse/Treehouse/Presentation/CreateTreehouse/CreateTreehouseScene/Views/SendInvitationView.swift
  Treehouse/Treehouse/Presentation/CreateTreehouse/CreateTreehouseScene/Views/TreehouseCreatingSuccessView.swift
  Treehouse/Treehouse/Presentation/Feed/FeedScene/Views/PostDetailView.swift
Labels: ✨ Feat, 🐰 영서

#77 [Feat] #75 - SwiftData 를 활용한 유저 데이터 저장 및 프로필 수정 관련 로직 변경
  Treehouse/Treehouse.xcodeproj/project.pbxproj
  Treehouse/Treehouse/Application/TreehouseApp.swift
  Treehouse/Treehouse/Global/Components/TabView/TreeTabView.swift
  Treehouse/Treehouse/Global/Extension/Data+.swift
  Treehouse/Treehouse/Global/Extension/Image+.swift
  Treehouse/Treehouse/Global/Literals/StringLiterals.swift
  Treehouse/Treehouse/Global/SwiftData/UserInfoData.swift
  Treehouse/Treehouse/Global/SwiftData/UserInfoDataSource.swift
  Treehouse/Treehouse/Global/SwiftData/UserInfoViewModel.swift
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/ViewModels/UserSettingViewModel.swift
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/Views/ShowMemberProfileView.swift
  Treehouse/Treehouse/Presentation/Feed/FeedScene/Views/EditPostPopupView.swift
  Treehouse/Treehouse/Presentation/Feed/FeedScene/Views/FeedHomeView.swift
  Treehouse/Treehouse/Presentation/Feed/FeedScene/Views/FeedView.swift
  Treehouse/Treehouse/Presentation/Feed/FeedScene/Views/PostDetailView.swift
  Treehouse/Treehouse/Presentation/Feed/FeedScene/Views/SinglePostView.swift
  Treehouse/Treehouse/Presentation/Profile/Views/EditProfileView.swift
  Treehouse/Treehouse/Presentation/Profile/Views/MemberProfileView.swift
  Treehouse/Treehouse/Presentation/Profile/Views/MyProfileView.swift
  Treehouse/Treehouse/Presentation/Profile/Views/UserInfoView.swift
  Treehouse/Treehouse/ViewRouter/ProfileRouter.swift
Labels: ✨ Feat, 🦁 준혁

#80 [Feat] #79 - 디바이스 내의 연락처 정보를 가져오는 로직 구현
  Treehouse/Treehouse.xcodeproj/project.pbxproj
  Treehouse/Treehouse/Global/Extension/Image+.swift
  Treehouse/Treehouse/Global/Extension/String+.swift
  Treehouse/Treehouse/Global/Literals/StringLiterals.swift
  Treehouse/Treehouse/Info.plist
  Treehouse/Treehouse/Presentation/Auth/InvitationScene/Models/PhoneNumberStruct.swift
  Treehouse/Treehouse/Presentation/Auth/InvitationScene/Models/UserPhoneNumberInfo.swift
  Treehouse/Treehouse/Presentation/Auth/InvitationScene/ViewModels/PhoneNumberViewModel.swift
  Treehouse/Treehouse/Presentation/Auth/InvitationScene/Views/InviteBranchView.swift
  Treehouse/Treehouse/Presentation/Auth/InvitationScene/Views/PhoneNumberRow.swift
  Treehouse/Treehouse/Presentation/Auth/InvitationScene/Views/PhoneNumberSearchBar.swift
  Treehouse/Treehouse/Presentation/CreateTreehouse/CreateTreehouseScene/Views/SendInvitationView.swift
  Treehouse/Treehouse/Presentation/Feed/FeedScene/Views/PostDetailView.swift
Labels: ✨ Feat, 🦁 준혁

#81 [Feat] #78 - 토큰 재발급 API 구현 및 기존 API 와 연결
  Treehouse/Treehouse.xcodeproj/project.pbxproj
  Treehouse/Treehouse/Network/Base/BaseResponse.swift
  Treehouse/Treehouse/Network/Base/NetworkServiceManager.swift
  Treehouse/Treehouse/Network/Feed/FeedService.swift
  Treehouse/Treehouse/Network/Invitation/InvitationService.swift
  Treehouse/Treehouse/Network/Protocols/NetworkServiceable.swift
  Treehouse/Treehouse/Network/Register/DTO/Response/PostReissueTokenResponseDTO.swift
  Treehouse/Treehouse/Network/Register/RegisterService.swift
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/ViewModels/UserSettingViewModel.swift
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/Views/ReceivedFirstInvitaionView.swift
Labels: ⚒️ Fix, 🌎 Network, ⚙️ Setting, 🦁 준혁

#86 [Fix] #85 - Image 크기 줄이는 로직 추가 및 회원 가입 시 필요한 이미지 관련 코드 수정
  Treehouse/Treehouse/Domain/Entities/Register/ExistsUserLoginResponseEntity.swift
  Treehouse/Treehouse/Global/Extension/Image+.swift
  Treehouse/Treehouse/Global/PhotoPicker/PhotoPickerManager.swift
  Treehouse/Treehouse/Global/SwiftData/UserInfoViewModel.swift
  Treehouse/Treehouse/Network/Register/DTO/Response/PostExistsUserLoginResponseDTO.swift
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/ViewModels/UserPhoneViewModel.swift
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/ViewModels/UserSettingViewModel.swift
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/Views/SetMemberBioView.swift
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/Views/SetMemberProfileImage.swift
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/Views/ShowMemberProfileView.swift
Labels: ⚒️ Fix, 🦁 준혁

#88 [Feat] #87 - Treehouse, Member API (UseCase, Repository) 설정 구현
  Treehouse/Treehouse.xcodeproj/project.pbxproj
  Treehouse/Treehouse/Data/Repositories/MemberRepositoryImpl.swift
  Treehouse/Treehouse/Data/Repositories/TreehouseRepositoryImpl.swift
  Treehouse/Treehouse/Domain/Entities/Member/PatchModifyMyProfileResponseEntity.swift
  Treehouse/Treehouse/Domain/Entities/Member/ReadMemberFeedResponseEntity.swift
  Treehouse/Treehouse/Domain/Entities/Member/ReadMemberInfoResponseEntity.swift
  Treehouse/Treehouse/Domain/Entities/Member/ReadMyProfileInfoResponseEntity.swift
  Treehouse/Treehouse/Domain/Entities/Treehouse/CreateTreehouseResponseEntity.swift
  Treehouse/Treehouse/Domain/Entities/Treehouse/ReadTreehouseInfoResponseEntity.swift
  Treehouse/Treehouse/Domain/RepositoryProtocol/MemberRepositoryProtocol.swift
  Treehouse/Treehouse/Domain/RepositoryProtocol/TreehouseRepositoryProtocol.swift
  Treehouse/Treehouse/Domain/UseCases/Member/ModifyMyProfileUseCase.swift
  Treehouse/Treehouse/Domain/UseCases/Member/ReadMemberFeedUseCase.swift
  Treehouse/Treehouse/Domain/UseCases/Member/ReadMemberInfoUseCase.swift
  Treehouse/Treehouse/Domain/UseCases/Member/ReadMyProfileInfoUseCase.swift
  Treehouse/Treehouse/Domain/UseCases/Treehouse/CreateTreehouseUseCase.swift
  Treehouse/Treehouse/Domain/UseCases/Treehouse/ReadTreehouseInfoUseCase.swift
  Treehouse/Treehouse/Network/Feed/DTO/Response/GetReadFeedPostsListResponseDTO.swift
  Treehouse/Treehouse/Network/Member/DTO/Request/PatchModifyMyProfileRequestDTO.swift
  Treehouse/Treehouse/Network/Member/DTO/Response/GetReadMemberFeedResponseDTO.swift
  Treehouse/Treehouse/Network/Member/DTO/Response/GetReadMemberInfoResponseDTO.swift
  Treehouse/Treehouse/Network/Member/DTO/Response/GetReadMyProfileInfoResponseDTO.swift
  Treehouse/Treehouse/Network/Member/DTO/Response/PatchModifyMyProfileResponseDTO.swift
  Treehouse/Treehouse/Network/Member/MemberAPI.swift
  Treehouse/Treehouse/Network/Member/MemberService.swift
  Treehouse/Treehouse/Network/Treehouse/DTO/Request/PostCreateTreehouseRequestDTO.swift
  Treehouse/Treehouse/Network/Treehouse/DTO/Response/GetReadTreehouseInfoResponseDTO.swift
  Treehouse/Treehouse/Network/Treehouse/DTO/Response/PostCreateTreehouseResponseDTO.swift
  Treehouse/Treehouse/Network/Treehouse/TreehouseAPI.swift
  Treehouse/Treehouse/Network/Treehouse/TreehouseService.swift
Labels: ✨ Feat, 🌎 Network, 🦁 준혁
