Repository Team-Shaka/Tree-House-iOS, pull requests merged in 2024-04, with the labels that each got.

#3 [Fix] #2 - UIImageView+ 파일명 수정
  Treehouse/Treehouse.xcodeproj/project.pbxproj
  Treehouse/Treehouse/Global/Extension/UIImageView+.swift
Labels: ⚒️Fix, 🐺태경

#9 [Feat] #7 - Text 행간에 대한 로직 구현
  Treehouse/Treehouse.xcodeproj/project.pbxproj
  Treehouse/Treehouse/Global/Extension/NSObject+.swift
  Treehouse/Treehouse/Global/Extension/UIButton+.swift
  Treehouse/Treehouse/Global/Extension/UIColor+.swift
  Treehouse/Treehouse/Global/Extension/UIImage+.swift
  Treehouse/Treehouse/Global/Extension/UIImageView+.swift
  Treehouse/Treehouse/Global/Extension/UILabel+.swift
  Treehouse/Treehouse/Global/Extension/UIStackView+.swift
  Treehouse/Treehouse/Global/Extension/UITextField+.swift
  Treehouse/Treehouse/Global/Extension/UIViewController+.swift
  Treehouse/Treehouse/Global/Extension/View+.swift
  Treehouse/Treehouse/Global/Literals/FontLiterals.swift
Labels: ✨ Feat, 🦁 준혁

#13 [Feat] #12 - SetUserIdView 및 userId 유효성 로직 구현
  Treehouse/Treehouse.xcodeproj/project.pbxproj
  Treehouse/Treehouse/Global/Literals/StringLiterals.swift
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/Views/SetUserIdView.swift
  Treehouse/Treehouse/Presentation/Auth/TextFieldStateType.swift
Labels: ✨ Feat, 🦁 준혁

#15 [Feat] #14 - ShowUserProfileView 구현
  Treehouse/Treehouse.xcodeproj/project.pbxproj
  Treehouse/Treehouse/Global/Literals/StringLiterals.swift
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/img_polygon.imageset/Contents.json
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/img_polygon.imageset/Polygon.png
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/img_polygon.imageset/Polygon@2x.png
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/img_polygon.imageset/Polygon@3x.png
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/Views/SetUserIdView.swift
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/Views/ShowUserProfileView.swift
Labels: ✨ Feat, 🦁 준혁

#17 [FEAT] 회원가입 - 전화번호 입력뷰 UI 작업
  Treehouse/Treehouse.xcodeproj/project.pbxproj
  Treehouse/Treehouse/Global/Extension/String+.swift
  Treehouse/Treehouse/Global/Extension/View+.swift
  Treehouse/Treehouse/Global/Literals/FontLiterals.swift
  Treehouse/Treehouse/Global/Literals/StringLiterals.swift
  Treehouse/Treehouse/Global/Resources/Font/Pretendard-Medium.otf
  Treehouse/Treehouse/Info.plist
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/Views/SetPhoneNumberView.swift
Labels: ✨ Feat, 🐰 영서

#18 [Feat] #11 - 회원가입 뷰 UI 작업
  Treehouse/Treehouse.xcodeproj/project.pbxproj
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/error.imageset/Contents.json
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/error.imageset/error.png
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/error.imageset/error@2x.png
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/error.imageset/error@3x.png
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/Views/LoginView.swift
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/Views/UnableRegisterView.swift
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/Views/VerificationView.swift
Labels: ✨ Feat, 🐺 태경

#20 [Feat] #16 - 받은 초대장 확인뷰 UI 구현
  Treehouse/Treehouse.xcodeproj/project.pbxproj
  Treehouse/Treehouse/Global/Extension/View+.swift
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/GrayScale/gray1.colorset/Contents.json
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/GrayScale/gray2.colorset/Contents.json
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/GrayScale/grayscaleWhite.colorset/Contents.json
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/img_dumy.imageset/Contents.json
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/img_dumy.imageset/img_dumy.png
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/treehouseTitle.imageset/Contents.json
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/treehouseTitle.imageset/treehouseTitle.png
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/treehouseTitle.imageset/treehouseTitle@2x.png
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/treehouseTitle.imageset/treehouseTitle@3x.png
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/Views/DrawingView.swift
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/Views/ReceivedFirstInvitaionView.swift
Labels: ✨ Feat, 🦁 준혁

#21 [Feat] 회원가입 뷰 텍스트 행간 높이 조정
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/Views/LoginView.swift
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/Views/UnableRegisterView.swift
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/Views/VerificationView.swift
Labels: ✨ Feat, 🐺 태경

#24 [Feat] #23 - 회원가입 - 멤버 프로필 설정 완료 뷰 UI 구현
  Treehouse/Treehouse.xcodeproj/project.pbxproj
  Treehouse/Treehouse/Global/Extension/View+.swift
  Treehouse/Treehouse/Global/Literals/StringLiterals.swift
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/img_profile_background.imageset/Contents.json
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/img_profile_background.imageset/img_profile_background.png
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/img_profile_background.imageset/img_profile_background@2x.png
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/img_profile_background.imageset/img_profile_background@3x.png
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/Views/ShowMemberProfileView.swift
Labels: ✨ Feat, 🐰 영서

#29 [Feat] #27 - NotificatoinView UI 구현 및 모델 생성
  Treehouse/Treehouse.xcodeproj/project.pbxproj
  Treehouse/Treehouse/Global/Literals/StringLiterals.swift
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/Notification/Contents.json
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/Notification/ic_invitation_gray.imageset/Contents.json
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/Notification/ic_invitation_gray.imageset/ic_invitation_gray.png
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/Notification/ic_invitation_gray.imageset/ic_invitation_gray@2x.png
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/Notification/ic_invitation_gray.imageset/ic_invitation_gray@3x.png
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/Notification/img_notiempty.imageset/Contents.json
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/Notification/img_notiempty.imageset/img_notiempty.png
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/Notification/img_notiempty.imageset/img_notiempty@2x.png
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/Notification/img_notiempty.imageset/img_notiempty@3x.png
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/img_dummy.imageset/Contents.json
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/img_dummy.imageset/img_dumy.png
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/img_dummy_2.imageset/Contents.json
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/img_dummy_2.imageset/KakaoTalk_Photo_2024-02-16-17-11-12.jpeg
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/Views/ReceivedFirstInvitaionView.swift
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/Views/SetMemberBioView.swift
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/Views/SetMemberProfileImage.swift
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/Views/ShowMemberProfileView.swift
  Treehouse/Treehouse/Presentation/Notification/NotificationScene/Models/NotificationStruct.swift
  Treehouse/Treehouse/Presentation/Notification/NotificationScene/Models/NotificationType.swift
  Treehouse/Treehouse/Presentation/Notification/NotificationScene/Views/NotificationRow.swift
  Treehouse/Treehouse/Presentation/Notification/NotificationScene/Views/NotificationView.swift
Labels: ✨ Feat, 🐰 영서

#30 [Feat] #26 - 초대 브랜치 뷰 UI 작업
  Treehouse/Treehouse.xcodeproj/project.pbxproj
  Treehouse/Treehouse/Global/Literals/StringLiterals.swift
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/ic_tooltip.imageset/Contents.json
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/ic_tooltip.imageset/ic_tooltip.svg
  Treehouse/Treehouse/Presentation/Auth/InvitationScene/Models/AvailableInvitationStruct.swift
  Treehouse/Treehouse/Presentation/Auth/InvitationScene/Models/PhoneNumberStruct.swift
  Treehouse/Treehouse/Presentation/Auth/InvitationScene/Views/DarkGreenLetterView.swift
  Treehouse/Treehouse/Presentation/Auth/InvitationScene/Views/GreenLetterView.swift
  Treehouse/Treehouse/Presentation/Auth/InvitationScene/Views/InvitationTooltip.swift
  Treehouse/Treehouse/Presentation/Auth/InvitationScene/Views/InviteBranchView.swift
  Treehouse/Treehouse/Presentation/Auth/InvitationScene/Views/PhoneNumberRow.swift
  Treehouse/Treehouse/Presentation/Auth/InvitationScene/Views/PhoneNumberSearchBar.swift
Labels: ✨ Feat, 🐺 태경

#32 [Feat] #28 - 초대장 List 및 Detail 초대장 구현
  Treehouse/Treehouse.xcodeproj/project.pbxproj
  Treehouse/Treehouse/Global/Components/InvitationView.swift
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/GrayScale/alertBackground.colorset/Contents.json
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/img_group.imageset/Contents.json
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/img_group.imageset/img_group.png
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/img_group.imageset/img_group@2x.png
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/img_group.imageset/img_group@3x.png
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/img_group_person.imageset/Contents.json
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/img_group_person.imageset/img_group_person.svg
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/img_invitationempty.imageset/Contents.json
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/img_invitationempty.imageset/img_invitationempty.png
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/img_invitationempty.imageset/img_invitationempty@2x.png
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/img_invitationempty.imageset/img_invitationempty@3x.png
  Treehouse/Treehouse/Presentation/Auth/InvitationScene/Models/ReceivedInvitationModel.swift
  Treehouse/Treehouse/Presentation/Auth/InvitationScene/ViewModel/ReceivedInvitationViewModel.swift
  Treehouse/Treehouse/Presentation/Auth/InvitationScene/Views/InvitationAlertView.swift
  Treehouse/Treehouse/Presentation/Auth/InvitationScene/Views/ReceivedInvitationRowView.swift
  Treehouse/Treehouse/Presentation/Auth/InvitationScene/Views/ReceivedInvitationView.swift
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/Views/DrawingView.swift
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/Views/ReceivedFirstInvitaionView.swift
Labels: ✨ Feat, 🦁 준혁
