Repository Team-Shaka/Tree-House-iOS, pull requests merged in 2024-05, with the labels that each got.

#34 [Feat] #33 - 댓글, 대댓글 UI 및 이모지 UI, 로직 구현
  Treehouse/Treehouse.xcodeproj/project.pbxproj
  Treehouse/Treehouse/Global/Extension/View+.swift
  Treehouse/Treehouse/Presentation/Auth/InvitationScene/ViewModels/ReceivedInvitationViewModel.swift
  Treehouse/Treehouse/Presentation/Feed/FeedContentScene/Models/CommentModel.swift
  Treehouse/Treehouse/Presentation/Feed/FeedContentScene/ViewModels/FeedContentViewModel.swift
  Treehouse/Treehouse/Presentation/Feed/FeedContentScene/Views/CommentView.swift
  Treehouse/Treehouse/Presentation/Feed/FeedContentScene/Views/EmojiListView.swift
  Treehouse/Treehouse/Presentation/Feed/FeedContentScene/Views/FeedContentView.swift
  Treehouse/Treehouse/Presentation/Feed/FeedContentScene/Views/FlowlayoutStack.swift
Labels: ✨ Feat, 🦁 준혁

#39 [Setting] #36 - Repository Pattern 적용하기
  Treehouse/Treehouse.xcodeproj/project.pbxproj
  Treehouse/Treehouse/Data/DataMapping/Register/CheckNameResponseDTO.swift
  Treehouse/Treehouse/Data/Repositories/DefaultRegisterRepository.swift
  Treehouse/Treehouse/Domain/Entities/Register/CheckNameResponseEntity.swift
  Treehouse/Treehouse/Domain/Repositories/RegisterRepository.swift
  Treehouse/Treehouse/Domain/UseCases/Register/PostCheckNameUseCase.swift
  Treehouse/Treehouse/Network/Register/RegisterAPI.swift
  Treehouse/Treehouse/Network/Register/RegisterService.swift
Labels: ⚙️ Setting, 🐺 태경

#40 [Feat] #38 - 서버 통신을 위한 API 기초 설정 구현
  Treehouse/Treehouse.xcodeproj/project.pbxproj
  Treehouse/Treehouse.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Treehouse/Treehouse/Global/Resources/Config.swift
  Treehouse/Treehouse/Info.plist
  Treehouse/Treehouse/Network/Base/BaseRequest.swift
  Treehouse/Treehouse/Network/Base/BaseResponse.swift
  Treehouse/Treehouse/Network/Base/HttpMethod.swift
  Treehouse/Treehouse/Network/Invitation/DTO/Request/PostWhetherInvitationsRequestDTO.swift
  Treehouse/Treehouse/Network/Invitation/DTO/Response/GetCheckAvailableInvitationResponseDTO.swift
  Treehouse/Treehouse/Network/Invitation/DTO/Response/GetCheckInvitationsReponseDTO.swift
  Treehouse/Treehouse/Network/Invitation/DTO/Response/PostWhetherInvitationsResponseDTO.swift
  Treehouse/Treehouse/Network/Invitation/InvitationAPI.swift
  Treehouse/Treehouse/Network/Notification/DTO/Response/GetCheckNotificationsResponseDTO.swift
  Treehouse/Treehouse/Network/Notification/NotificationAPI.swift
  Treehouse/Treehouse/Network/Register/DTO/Request/PostAcceptInvitationTreeMemberRequestDTO.swift
  Treehouse/Treehouse/Network/Register/DTO/Request/PostCheckUserNameRequestDTO.swift
  Treehouse/Treehouse/Network/Register/DTO/Request/PostRegisterTreeMemberRequestDTO.swift
  Treehouse/Treehouse/Network/Register/DTO/Request/PostRegisterUserRequestDTO.swift
  Treehouse/Treehouse/Network/Register/DTO/Request/PostReissueTokenRequestDTO.swift
  Treehouse/Treehouse/Network/Register/DTO/Response/PostAcceptInvitationTreeMemberResponseDTO.swift
  Treehouse/Treehouse/Network/Register/DTO/Response/PostCheckUserNameResponseDTO.swift
  Treehouse/Treehouse/Network/Register/DTO/Response/PostRegisterTreeMemberResponseDTO.swift
  Treehouse/Treehouse/Network/Register/DTO/Response/PostRegisterUserResponseDTO.swift
  Treehouse/Treehouse/Network/Register/DTO/Response/PostReissueTokenResponseDTO.swift
  Treehouse/Treehouse/Network/Register/RegisterAPI.swift
Labels: ✨ Feat, 🌎 Network, ⚙️ Setting, 🦁 준혁

#48 [Feat] #47 - Feed API 기본 세팅 구현
  Treehouse/Treehouse.xcodeproj/project.pbxproj
  Treehouse/Treehouse/Network/Feed/DTO/Request/PostCreateCommentRequestDTO.swift
  Treehouse/Treehouse/Network/Feed/DTO/Request/PostCreateFeedPostsRequestDTO.swift
  Treehouse/Treehouse/Network/Feed/DTO/Request/PostReactionCommentRequestDTO.swift
  Treehouse/Treehouse/Network/Feed/DTO/Request/PostReactionFeedPostRequestDTO.swift
  Treehouse/Treehouse/Network/Feed/DTO/Request/PostReportFeedCommentRequestDTO.swift
  Treehouse/Treehouse/Network/Feed/DTO/Request/PostReportFeedPostRequestDTO.swift
  Treehouse/Treehouse/Network/Feed/DTO/Response/GetReadCommentResponseDTO.swift
  Treehouse/Treehouse/Network/Feed/DTO/Response/GetReadDetailFeedPostsResponseDTO.swift
  Treehouse/Treehouse/Network/Feed/DTO/Response/GetReadFeedPostsListResponseDTO.swift
  Treehouse/Treehouse/Network/Feed/DTO/Response/PatchUpdateFeedPostResponseDTO.swift
  Treehouse/Treehouse/Network/Feed/DTO/Response/PostCreateCommentResponseDTO.swift
  Treehouse/Treehouse/Network/Feed/DTO/Response/PostCreateFeedPostsResponseDTO.swift
  Treehouse/Treehouse/Network/Feed/FeedAPI.swift
  Treehouse/Treehouse/Network/Feed/FeedService.swift
Labels: ⚙️ Setting, 🦁 준혁

#50 Feat/#44 Header View, Bottom Sheet, Tree Hall View 구현
  Treehouse/Treehouse.xcodeproj/project.pbxproj
  Treehouse/Treehouse/Global/Extension/View+.swift
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/Feed/ic_next_gray.imageset/Contents.json
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/Feed/ic_next_gray.imageset/ic_next_gray.png
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/Feed/ic_next_gray.imageset/ic_next_gray@2x.png
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/Feed/ic_next_gray.imageset/ic_next_gray@3x.png
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/Feed/ic_person_gray.imageset/Contents.json
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/Feed/ic_person_gray.imageset/ic_person_gray.png
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/Feed/ic_person_gray.imageset/ic_person_gray@2x.png
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/Feed/ic_person_gray.imageset/ic_person_gray@3x.png
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/Feed/img_profile.imageset/Contents.json
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/Feed/img_profile.imageset/img_profile.png
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/Feed/img_profile.imageset/img_profile@2x.png
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/Feed/img_profile.imageset/img_profile@3x.png
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/ic_voice.imageset/Contents.json
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/ic_voice.imageset/ic_voice.svg
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/ic_voice_person.imageset/Contents.json
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/ic_voice_person.imageset/ic_voice_person.svg
  Treehouse/Treehouse/Presentation/Feed/FeedScene/Models/GroupStruct.swift
  Treehouse/Treehouse/Presentation/Feed/FeedScene/Views/FeedHeaderView.swift
  Treehouse/Treehouse/Presentation/Feed/FeedScene/Views/GroupChangeBottomSheet.swift
  Treehouse/Treehouse/Presentation/Feed/FeedScene/Views/GroupRow.swift
  Treehouse/Treehouse/Presentation/Feed/FeedScene/Views/HeaderView.swift
  Treehouse/Treehouse/Presentation/Feed/FeedScene/Views/TreeHallView.swift
Labels: ✨ Feat, 🐺 태경
