Repository Team-Shaka/Tree-House-iOS, pull requests merged in 2024-06, with the labels that each got.

#52 [Feat] #51 - Repository 및 UseCase 를 이용한 API 연결, UI 수정
  Treehouse/Treehouse.xcodeproj/project.pbxproj
  Treehouse/Treehouse/Application/TreehouseApp.swift
  Treehouse/Treehouse/Data/Repositories/DefaultRegisterRepository.swift
  Treehouse/Treehouse/Data/Repositories/RegisterRepositoryImpl.swift
  Treehouse/Treehouse/Domain/Repositories/RegisterRepository.swift
  Treehouse/Treehouse/Domain/RepositoryProtocol/RegisterRepositoryProtocol.swift
  Treehouse/Treehouse/Domain/UseCases/Register/CheckNameUseCase.swift
  Treehouse/Treehouse/Domain/UseCases/Register/PostCheckNameUseCase.swift
  Treehouse/Treehouse/Global/Extension/View+.swift
  Treehouse/Treehouse/Global/Literals/FontLiterals.swift
  Treehouse/Treehouse/Global/Literals/StringLiterals.swift
  Treehouse/Treehouse/Network/Register/DTO/Response/PostCheckUserNameResponseDTO.swift
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/ViewModels/SetUserIdViewModel.swift
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/ViewModels/UserSettingViewModel.swift
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/Views/LoginView.swift
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/Views/ReceivedFirstInvitaionView.swift
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/Views/SetMemberBioView.swift
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/Views/SetMemberProfileImage.swift
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/Views/SetMemberProfileNameView.swift
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/Views/SetPhoneNumberView.swift
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/Views/SetUserIdView.swift
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/Views/ShowUserProfileView.swift
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/Views/UnableRegisterView.swift
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/Views/VerificationView.swift
  Treehouse/Treehouse/Presentation/Auth/TextFieldStateType.swift
  Treehouse/Treehouse/ViewRouter/RegisterRouter.swift
Labels: ✨ Feat, ⚒️ Fix, 🌎 Network, 🦁 준혁

#56 [Feat] #53 Register API 연결
  Treehouse/Treehouse.xcodeproj/project.pbxproj
  Treehouse/Treehouse/Data/Repositories/InvitationRepositoryImpl.swift
  Treehouse/Treehouse/Data/Repositories/RegisterRepositoryImpl.swift
  Treehouse/Treehouse/Domain/Entities/Invitation/AcceptInvitationTreeMemberEntity.swift
  Treehouse/Treehouse/Domain/Entities/Invitation/CheckInvitationsReponseEntity.swift
  Treehouse/Treehouse/Domain/Entities/Register/CheckUserPhoneResponseEntity.swift
  Treehouse/Treehouse/Domain/Entities/Register/RegisterTreeMemberResponseEntity.swift
  Treehouse/Treehouse/Domain/Entities/Register/RegisterUserResponseEntity.swift
  Treehouse/Treehouse/Domain/RepositoryProtocol/InvitationReposiotryProtocol.swift
  Treehouse/Treehouse/Domain/RepositoryProtocol/RegisterRepositoryProtocol.swift
  Treehouse/Treehouse/Domain/UseCases/Invitation/AcceptInvitationTreeMemberUseCase.swift
  Treehouse/Treehouse/Domain/UseCases/Invitation/CheckInvitationsUseCase.swift
  Treehouse/Treehouse/Domain/UseCases/Register/CheckUserPhone.swift
  Treehouse/Treehouse/Domain/UseCases/Register/RegisterTreeMemberUseCase.swift
  Treehouse/Treehouse/Domain/UseCases/Register/RegisterUserUseCase.swift
  Treehouse/Treehouse/Global/Components/InvitationView.swift
  Treehouse/Treehouse/Global/Literals/StringLiterals.swift
  Treehouse/Treehouse/Global/Resources/Config.swift
  Treehouse/Treehouse/Info.plist
  Treehouse/Treehouse/Network/Base/BaseRequest.swift
  Treehouse/Treehouse/Network/Base/NetworkRequest.swift
  Treehouse/Treehouse/Network/Invitation/DTO/Response/GetCheckInvitationsReponseDTO.swift
  Treehouse/Treehouse/Network/Invitation/InvitationAPI.swift
  Treehouse/Treehouse/Network/Invitation/InvitationService.swift
  Treehouse/Treehouse/Network/Register/DTO/Request/PostCheckUserPhoneRequestDTO.swift
  Treehouse/Treehouse/Network/Register/DTO/Response/PostAcceptInvitationTreeMemberResponseDTO.swift
  Treehouse/Treehouse/Network/Register/DTO/Response/PostCheckUserPhoneResponseDTO.swift
  Treehouse/Treehouse/Network/Register/DTO/Response/PostRegisterTreeMemberResponseDTO.swift
  Treehouse/Treehouse/Network/Register/DTO/Response/PostRegisterUserResponseDTO.swift
  Treehouse/Treehouse/Network/Register/RegisterAPI.swift
  Treehouse/Treehouse/Network/Register/RegisterService.swift
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/ViewModels/UserSettingViewModel.swift
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/Views/LoginView.swift
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/Views/ReceivedFirstInvitaionView.swift
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/Views/SetMemberBioView.swift
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/Views/SetMemberProfileImage.swift
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/Views/SetMemberProfileNameView.swift
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/Views/SetPhoneNumberView.swift
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/Views/SetUserIdView.swift
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/Views/ShowUserProfileView.swift
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/Views/UnableRegisterView.swift
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/Views/VerificationView.swift
Labels: ✨ Feat, 🌎 Network, 🦁 준혁

#61 [Feat] #54 - 프로필 뷰 구현
  Treehouse/Treehouse.xcodeproj/project.pbxproj
  Treehouse/Treehouse/Global/Literals/StringLiterals.swift
  Treehouse/Treehouse/Global/PhotoPicker/PhotoPickerManager.swift
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/Profile/Contents.json
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/Profile/btn_profileimg_1.imageset/Contents.json
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/Profile/btn_profileimg_1.imageset/btn_profileimg.png
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/Profile/btn_profileimg_1.imageset/btn_profileimg@2x.png
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/Profile/btn_profileimg_1.imageset/btn_profileimg@3x.png
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/Profile/btn_profileimg_2.imageset/Contents.json
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/Profile/btn_profileimg_2.imageset/btn_profileimg.png
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/Profile/btn_profileimg_2.imageset/btn_profileimg@2x.png
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/Profile/btn_profileimg_2.imageset/btn_profileimg@3x.png
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/Profile/img_user.imageset/Contents.json
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/Profile/img_user.imageset/img_user.png
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/Profile/img_user.imageset/img_user@2x.png
  Treehouse/Treehouse/Global/Resources/Assets.xcassets/Profile/img_user.imageset/img_user@3x.png
  Treehouse/Treehouse/Presentation/Feed/FeedScene/Views/BottomSheet.swift
  Treehouse/Treehouse/Presentation/Feed/FeedScene/Views/FeedHeaderView.swift
  Treehouse/Treehouse/Presentation/Feed/FeedScene/Views/MemberGroupRow.swift
  Treehouse/Treehouse/Presentation/Profile/Models/MemberGroupStruct.swift
  Treehouse/Treehouse/Presentation/Profile/Views/EditProfileView.swift
  Treehouse/Treehouse/Presentation/Profile/Views/MemberProfileView.swift
  Treehouse/Treehouse/Presentation/Profile/Views/MyProfileView.swift
  Treehouse/Treehouse/Presentation/Profile/Views/SettingView.swift
  Treehouse/Treehouse/ViewRouter/ProfileRouter.swift
Labels: ✨ Feat, 🐺 태경

#59 [Feat] #57 - 이모지 입력 가능한 View 구현
  Treehouse/Treehouse.xcodeproj/project.pbxproj
  Treehouse/Treehouse/Global/Components/CustomBottomSheet.swift
  Treehouse/Treehouse/Global/Extension/View+.swift
  Treehouse/Treehouse/Presentation/Feed/FeedContentScene/Models/emojiData.swift
  Treehouse/Treehouse/Presentation/Feed/FeedContentScene/ViewModels/FeedContentViewModel.swift
  Treehouse/Treehouse/Presentation/Feed/FeedContentScene/Views/ColorEmojiPopover.swift
  Treehouse/Treehouse/Presentation/Feed/FeedContentScene/Views/EmojiGridView.swift
  Treehouse/Treehouse/Presentation/Feed/FeedContentScene/Views/EmojiListView.swift
  Treehouse/Treehouse/Presentation/Feed/FeedContentScene/Views/FeedContentView.swift
  Treehouse/Treehouse/structuredEmojis.json
Labels: ✨ Feat, 🦁 준혁

#63 [Feat] #60 - Register API 완벽 구현
  Treehouse/Treehouse.xcodeproj/project.pbxproj
  Treehouse/Treehouse/Application/TreehouseApp.swift
  Treehouse/Treehouse/Data/Repositories/AWSImageRepositoryImpl.swift
  Treehouse/Treehouse/Data/Repositories/FeedRepositoryImpl.swift
  Treehouse/Treehouse/Data/Repositories/InvitationRepositoryImpl.swift
  Treehouse/Treehouse/Domain/Entities/AWSImage/PutUploadImagesResponseEntity.swift
  Treehouse/Treehouse/Domain/Entities/Feed/PresignedURLResponseEntity.swift
  Treehouse/Treehouse/Domain/Entities/Invitation/AcceptInvitationTreeMemberEntity.swift
  Treehouse/Treehouse/Domain/Entities/Invitation/CheckInvitationsReponseEntity.swift
  Treehouse/Treehouse/Domain/Entities/Register/RegisterTreeMemberResponseEntity.swift
  Treehouse/Treehouse/Domain/RepositoryProtocol/AWSImageRepositoryProtocol.swift
  Treehouse/Treehouse/Domain/RepositoryProtocol/FeedRepositoryProtocol.swift
  Treehouse/Treehouse/Domain/RepositoryProtocol/InvitationReposiotryProtocol.swift
  Treehouse/Treehouse/Domain/RepositoryProtocol/InvitationRepositoryProtocol.swift
  Treehouse/Treehouse/Domain/UseCases/AWSImage/UploadImageToAWSUseCase.swift
  Treehouse/Treehouse/Domain/UseCases/Feed/PresignedURLUseCase.swift
  Treehouse/Treehouse/Domain/UseCases/Invitation/AcceptInvitationTreeMemberUseCase.swift
  Treehouse/Treehouse/Domain/UseCases/Invitation/CheckInvitationsUseCase.swift
  Treehouse/Treehouse/Global/Components/TabView/TreeTabView.swift
  Treehouse/Treehouse/Global/Extension/UIApplication+.swift
  Treehouse/Treehouse/Global/Extension/UIImage+.swift
  Treehouse/Treehouse/Global/Extension/View+.swift
  Treehouse/Treehouse/Global/Literals/FontLiterals.swift
  Treehouse/Treehouse/Global/Literals/StringLiterals.swift
  Treehouse/Treehouse/Global/PhotoPicker/PhotoPickerManager.swift
  Treehouse/Treehouse/Network/AWSImage/AWSImageService.swift
  Treehouse/Treehouse/Network/AWSImage/DTO/Response/PutUploadImagesResponseDTO.swift
  Treehouse/Treehouse/Network/Feed/DTO/Request/PostPresignedURLRequestDTO.swift
  Treehouse/Treehouse/Network/Feed/DTO/Response/PostPresignedURLResponseDTO.swift
  Treehouse/Treehouse/Network/Feed/FeedAPI.swift
  Treehouse/Treehouse/Network/Feed/FeedService.swift
  Treehouse/Treehouse/Network/Invitation/DTO/Request/PostWhetherInvitationsRequestDTO.swift
  Treehouse/Treehouse/Network/Invitation/DTO/Response/PostWhetherInvitationsResponseDTO.swift
  Treehouse/Treehouse/Network/Invitation/InvitationAPI.swift
  Treehouse/Treehouse/Network/Invitation/InvitationService.swift
  Treehouse/Treehouse/Network/Register/DTO/Request/PostAcceptInvitationTreeMemberRequestDTO.swift
  Treehouse/Treehouse/Network/Register/DTO/Response/PostAcceptInvitationTreeMemberResponseDTO.swift
  Treehouse/Treehouse/Network/Register/DTO/Response/PostRegisterTreeMemberResponseDTO.swift
  Treehouse/Treehouse/Network/Register/RegisterAPI.swift
  Treehouse/Treehouse/Network/Register/RegisterService.swift
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/ViewModels/UserSettingViewModel.swift
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/Views/LoginView.swift
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/Views/ReceivedFirstInvitaionView.swift
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/Views/SetMemberBioView.swift
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/Views/SetMemberProfileImage.swift
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/Views/SetMemberProfileNameView.swift
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/Views/SetPhoneNumberView.swift
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/Views/SetUserIdView.swift
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/Views/ShowMemberProfileView.swift
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/Views/ShowUserProfileView.swift
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/Views/UnableRegisterView.swift
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/Views/VerificationView.swift
  Treehouse/Treehouse/Presentation/Auth/TextFieldStateType.swift
  Treehouse/Treehouse/Presentation/Feed/FeedScene/Views/FeedView.swift
  Treehouse/Treehouse/Presentation/Profile/Views/EditProfileView.swift
  Treehouse/Treehouse/ViewRouter/RegisterRouter.swift
  Treehouse/Treehouse/ViewRouter/ViewRouter.swift
Labels: ✨ Feat, ⚒️ Fix, 🌎 Network, ⚙️ Setting, 🦁 준혁

#65 [Feat] #58 - 게시글 수정 / 디테일 / 이미지 디테일뷰 구현
  Treehouse/Treehouse.xcodeproj/project.pbxproj
  Treehouse/Treehouse.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Treehouse/Treehouse/Global/ViewModifier/FullScreenModalModifier.swift
  Treehouse/Treehouse/Global/ViewModifier/MaxLengthModifier.swift
  Treehouse/Treehouse/Presentation/Feed/FeedScene/Views/DynamicHeightTextEditorView.swift
  Treehouse/Treehouse/Presentation/Feed/FeedScene/Views/EditPostPopupView.swift
  Treehouse/Treehouse/Presentation/Feed/FeedScene/Views/FeedView.swift
  Treehouse/Treehouse/Presentation/Feed/FeedScene/Views/ImageDetailCarouselView.swift
  Treehouse/Treehouse/Presentation/Feed/FeedScene/Views/PostAlertView.swift
  Treehouse/Treehouse/Presentation/Feed/FeedScene/Views/PostDetailView.swift
  Treehouse/Treehouse/Presentation/Feed/FeedScene/Views/SinglePostView.swift
  Treehouse/Treehouse/Presentation/Notification/NotificationScene/Views/NotificationView.swift
Labels: ✨ Feat, 🐰 영서

#68 [Feat] #66 - 게시글 및 댓글 바텀시트 구현 / 연결
  Treehouse/Treehouse.xcodeproj/project.pbxproj
  Treehouse/Treehouse/Presentation/Feed/FeedScene/Views/FeedBottomSheetRowView.swift
  Treehouse/Treehouse/Presentation/Feed/FeedScene/Views/PostDetailView.swift
  Treehouse/Treehouse/Presentation/Feed/FeedScene/Views/SinglePostView.swift
Labels: ✨ Feat, 🐰 영서

#67 [Feat] #62 - 초대장 게이지 및 개수 조회 API 연동
  Treehouse/Treehouse.xcodeproj/project.pbxproj
  Treehouse/Treehouse.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Treehouse/Treehouse/Data/Repositories/InvitationRepositoryImpl.swift
  Treehouse/Treehouse/Domain/Entities/Invitation/CheckAvailableInvitationReponseEntity.swift
  Treehouse/Treehouse/Domain/RepositoryProtocol/InvitationRepositoryProtocol.swift
  Treehouse/Treehouse/Domain/UseCases/Invitation/CheckInvitationsUseCase.swift
  Treehouse/Treehouse/Domain/UseCases/Invitation/ChecklAvailableInvitationUseCase.swift
  Treehouse/Treehouse/Global/PhotoPicker/PhotoPickerManager.swift
  Treehouse/Treehouse/Network/Invitation/DTO/Response/GetCheckAvailableInvitationResponseDTO.swift
  Treehouse/Treehouse/Network/Invitation/InvitationService.swift
  Treehouse/Treehouse/Presentation/Auth/InvitationScene/ViewModels/InvitationViewModel.swift
  Treehouse/Treehouse/Presentation/Auth/InvitationScene/Views/InviteBranchView.swift
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/Views/SetMemberProfileImage.swift
  Treehouse/Treehouse/Presentation/Auth/RegisterScene/Views/VerificationView.swift
Labels: ✨ Feat, 🌎 Network, 🐺 태경

#74 [Feat] #71 - FeedHomeView 화면 전환 및 View 수정
  Treehouse/Treehouse.xcodeproj/project.pbxproj
  Treehouse/Treehouse/Global/Components/TabView/TreeTabView.swift
  Treehouse/Treehouse/Presentation/Feed/FeedScene/Views/FeedBottomSheetRowView.swift
  Treehouse/Treehouse/Presentation/Feed/FeedScene/Views/FeedHomeView.swift
  Treehouse/Treehouse/Presentation/Feed/FeedScene/Views/FeedView.swift
  Treehouse/Treehouse/Presentation/Feed/FeedScene/Views/PostDetailView.swift
  Treehouse/Treehouse/Presentation/Feed/FeedScene/Views/SinglePostView.swift
  Treehouse/Treehouse/Presentation/Notification/NotificationScene/Views/NotificationView.swift
  Treehouse/Treehouse/Presentation/Profile/Views/EditProfileView.swift
  Treehouse/Treehouse/Presentation/Profile/Views/MemberProfileView.swift
  Treehouse/Treehouse/Presentation/Profile/Views/MyProfileView.swift
  Treehouse/Treehouse/Presentation/Profile/Views/UserInfoView.swift
  Treehouse/Treehouse/ViewRouter/FeedRouter.swift
  Treehouse/Treehouse/ViewRouter/ProfileRouter.swift
  Treehouse/Treehouse/ViewRouter/ViewRouter.swift
Labels: ✨ Feat, 🦁 준혁
